name: pfabricate
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - bcftools
  - click
  - scipy=1.4
  - scikit-allel
  - jupyter
  - seaborn
  - pysam
  - numba
  - flake8
  - black
  - pytest
  - pip
